library(quantmod)
library(rlms)
library(rusquant)
library(ggplot2)
library(dplyr)
library(car)
library(glmnet)
library(devtools)
library(lmtest)
library(xts)
library(zoo)
library(xts)
library(LSMonteCarlo)
library(rmarkdown)
library(pandoc)
library(knitr)
library(installr)
library(fOptions)
library(MASS)
library(tidyr)
library(ghyp)
library(xtable)
library(statmod)
options(stable.floating = FALSE)
options(xtable.timestamp = "")

